In [53]:
pip install google-cloud-bigquery pandas pyarrow db-dtypes requests

Requirement already satisfied: google-cloud-bigquery in /opt/python/envs/default_3_11/lib/python3.11/site-packages (3.44.0)
Requirement already satisfied: pandas in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: pyarrow in /opt/python/envs/default_3_11/lib/python3.11/site-packages (23.0.1)
Requirement already satisfied: db-dtypes in /opt/python/envs/default_3_11/lib/python3.11/site-packages (1.7.1)
Requirement already satisfied: requests in /opt/python/envs/default_3_11/lib/python3.11/site-packages (2.33.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (2.34.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.57.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.7.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.10.2)
Requirement already satisfied: packaging>=24.2.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (3.16)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from requests) (2026.5.20)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.75.2)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.28.4)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.83.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.83.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (50.0.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from grpcio<2.0.0,>=1.59.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pandas) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.1)
Requirement already satisfied: pycparser in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/python/envs/default_3_11/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [54]:
import os

print("Project ID found:", bool(os.environ.get("gcl_project_id")))
print("GCP service account key found:", bool(os.environ.get("GCP_SA_KEY")))

Project ID found: True
GCP service account key found: True

In [55]:
import sys, json
import pandas as pd
from google.cloud import bigquery

PROJECT_ID = os.environ["gcl_project_id"]   # ← замінити на свій проєкт
LOCATION   = "EU"

creds = None

if "google.colab" in sys.modules:                  # Colab
    from google.colab import auth
    auth.authenticate_user()

elif os.environ.get("GCP_SA_KEY"):                 # Datalore: ключ у змінній середовища
    from google.oauth2 import service_account
    creds = service_account.Credentials.from_service_account_info(
        json.loads(os.environ["GCP_SA_KEY"]),
        scopes=["https://www.googleapis.com/auth/cloud-platform"])

client = bigquery.Client(project=PROJECT_ID, location=LOCATION, credentials=creds)
print("проєкт:", client.project)

проєкт: datalab-504011

In [56]:
# Завдання 6. Ноутбук 05 — історична таблиця фактів і злиття

# Завдання 6.1. Прочитайте з nbu_raw.raw_rates рядки тільки за сьогодні.

query = f"""
SELECT *
FROM `{PROJECT_ID}.nbu_raw.raw_rates`
WHERE business_date = CURRENT_DATE()
"""

# Завдання 6.2. Розгорніть payload, нормалізуйте значення й приберіть дублікати усередині свого набору

raw_rates_bq = client.query(query).to_dataframe()
raw_rates_bq

payload = pd.json_normalize(raw_rates_bq["payload"].map(json.loads))

payload["ingested_at"] = raw_rates_bq["ingested_at"].values
payload["business_date"] = raw_rates_bq["business_date"].values

payload["cc"] = payload["cc"].str.strip().str.upper()
payload["txt"] = payload["txt"].str.strip()
payload["r030"] = payload["r030"].astype("Int64")

payload = payload.sort_values("ingested_at").drop_duplicates(subset=["business_date", "cc"], keep="last").reset_index(drop=True)


payload

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,cc,exchangedate,r030,rate,special,txt,ingested_at,business_date
0,DZD,31.08.2026,12,0.334950,None,Алжирський динар,2026-08-29 11:56:16.108246,2026-08-29
1,AUD,31.08.2026,36,32.049200,None,Австралійський долар,2026-08-29 11:56:16.108263,2026-08-29
2,BDT,31.08.2026,50,0.363330,None,Така,2026-08-29 11:56:16.108275,2026-08-29
3,CAD,31.08.2026,124,32.166200,None,Канадський долар,2026-08-29 11:56:16.108286,2026-08-29
4,CNY,31.08.2026,156,6.628100,None,Юань Женьміньбі,2026-08-29 11:56:16.108350,2026-08-29
5,CZK,31.08.2026,203,2.148200,None,Чеська крона,2026-08-29 11:56:16.108371,2026-08-29
6,DKK,31.08.2026,208,6.940800,None,Данська крона,2026-08-29 11:56:16.108382,2026-08-29
7,HKD,31.08.2026,344,5.682700,None,Гонконгівський долар,2026-08-29 11:56:16.108394,2026-08-29
8,HUF,31.08.2026,348,0.142161,None,Форинт,2026-08-29 11:56:16.108405,2026-08-29
9,INR,31.08.2026,356,0.467030,None,Індійська рупія,2026-08-29 11:56:16.108415,2026-08-29
10,IDR,31.08.2026,360,0.002518,None,Рупія,2026-08-29 11:56:16.108424,2026-08-29
11,ILS,31.08.2026,376,14.980500,None,Новий ізраїльський шекель,2026-08-29 11:56:16.108434,2026-08-29
12,JPY,31.08.2026,392,0.279020,None,Єна,2026-08-29 11:56:16.108443,2026-08-29
13,KZT,31.08.2026,398,0.096048,None,Теньге,2026-08-29 11:56:16.108452,2026-08-29
14,KRW,31.08.2026,410,0.032410,None,Вона,2026-08-29 11:56:16.108462,2026-08-29
15,LBP,31.08.2026,422,0.000497,None,Ліванський фунт,2026-08-29 11:56:16.108472,2026-08-29
16,MYR,31.08.2026,458,11.071600,None,Малайзійський ринггіт,2026-08-29 11:56:16.108481,2026-08-29
17,MXN,31.08.2026,484,2.627800,None,Мексиканське песо,2026-08-29 11:56:16.108491,2026-08-29
18,MDL,31.08.2026,498,2.579600,None,Молдовський лей,2026-08-29 11:56:16.108500,2026-08-29
19,NZD,31.08.2026,554,26.485700,None,Новозеландський долар,2026-08-29 11:56:16.108509,2026-08-29
20,NOK,31.08.2026,578,4.776700,None,Норвезька крона,2026-08-29 11:56:16.108519,2026-08-29
21,SAR,31.08.2026,682,11.865700,None,Саудівський ріял,2026-08-29 11:56:16.108528,2026-08-29
22,SGD,31.08.2026,702,35.041300,None,Сінгапурський долар,2026-08-29 11:56:16.108538,2026-08-29
23,VND,31.08.2026,704,0.001708,None,Донг,2026-08-29 11:56:16.108563,2026-08-29
24,ZAR,31.08.2026,710,2.784100,None,Ренд,2026-08-29 11:56:16.108572,2026-08-29
25,SEK,31.08.2026,752,4.679700,None,Шведська крона,2026-08-29 11:56:16.108582,2026-08-29
26,CHF,31.08.2026,756,55.420700,None,Швейцарський франк,2026-08-29 11:56:16.108592,2026-08-29
27,THB,31.08.2026,764,1.351820,None,Бат,2026-08-29 11:56:16.108601,2026-08-29
28,AED,31.08.2026,784,12.129200,None,Дирхам ОАЕ,2026-08-29 11:56:16.108611,2026-08-29
29,TND,31.08.2026,788,15.325000,None,Туніський динар,2026-08-29 11:56:16.108620,2026-08-29
30,EGP,31.08.2026,818,0.886600,None,Єгипетський фунт,2026-08-29 11:56:16.108632,2026-08-29
31,GBP,31.08.2026,826,60.523200,None,Фунт стерлінгів,2026-08-29 11:56:16.108642,2026-08-29
32,USD,31.08.2026,840,44.550500,N,Долар США,2026-08-29 11:56:16.108651,2026-08-29
33,RSD,31.08.2026,941,0.442050,None,Сербський динар,2026-08-29 11:56:16.108660,2026-08-29
34,AZN,31.08.2026,944,26.206200,None,Азербайджанський манат,2026-08-29 11:56:16.108670,2026-08-29
35,RON,31.08.2026,946,9.866100,None,Румунський лей,2026-08-29 11:56:16.108679,2026-08-29
36,TRY,31.08.2026,949,0.923400,None,Турецька ліра,2026-08-29 11:56:16.108693,2026-08-29
37,XDR,31.08.2026,960,61.082600,None,СПЗ (спеціальні права запозичення),2026-08-29 11:56:16.108703,2026-08-29
38,EUR,31.08.2026,978,51.880400,None,Євро,2026-08-29 11:56:16.108712,2026-08-29
39,GEL,31.08.2026,981,17.043400,None,Ларі,2026-08-29 11:56:16.108721,2026-08-29
40,PLN,31.08.2026,985,11.962500,None,Злотий,2026-08-29 11:56:16.108730,2026-08-29
41,XAU,31.08.2026,959,204632.030000,None,Золото,2026-08-29 11:56:16.108739,2026-08-29
42,XAG,31.08.2026,961,3127.580000,None,Срібло,2026-08-29 11:56:16.108748,2026-08-29
43,XPT,31.08.2026,962,84438.750000,None,Платина,2026-08-29 11:56:16.108757,2026-08-29
44,XPD,31.08.2026,964,62877.770000,None,Паладій,2026-08-29 11:56:16.108766,2026-08-29

In [57]:
# Завдання 6.2. Розгорніть payload, нормалізуйте значення й приберіть дублікати усередині свого набору
payload["ingested_at"] = raw_rates_bq["ingested_at"]
payload["business_date"] = raw_rates_bq["business_date"]

payload["cc"] = payload["cc"].str.strip().str.upper()
payload["txt"] = payload["txt"].str.strip()
payload["r030"] = payload["r030"].astype("Int64")

payload = payload.sort_values("ingested_at").drop_duplicates(subset=["business_date", "cc"], keep="last").reset_index(drop=True)


payload

,cc,exchangedate,r030,rate,special,txt,ingested_at,business_date
0,DZD,31.08.2026,12,0.334950,None,Алжирський динар,2026-08-29 11:56:16.108246+00:00,2026-08-29
1,AUD,31.08.2026,36,32.049200,None,Австралійський долар,2026-08-29 11:56:16.108263+00:00,2026-08-29
2,BDT,31.08.2026,50,0.363330,None,Така,2026-08-29 11:56:16.108275+00:00,2026-08-29
3,CAD,31.08.2026,124,32.166200,None,Канадський долар,2026-08-29 11:56:16.108286+00:00,2026-08-29
4,CNY,31.08.2026,156,6.628100,None,Юань Женьміньбі,2026-08-29 11:56:16.108350+00:00,2026-08-29
5,CZK,31.08.2026,203,2.148200,None,Чеська крона,2026-08-29 11:56:16.108371+00:00,2026-08-29
6,DKK,31.08.2026,208,6.940800,None,Данська крона,2026-08-29 11:56:16.108382+00:00,2026-08-29
7,HKD,31.08.2026,344,5.682700,None,Гонконгівський долар,2026-08-29 11:56:16.108394+00:00,2026-08-29
8,HUF,31.08.2026,348,0.142161,None,Форинт,2026-08-29 11:56:16.108405+00:00,2026-08-29
9,INR,31.08.2026,356,0.467030,None,Індійська рупія,2026-08-29 11:56:16.108415+00:00,2026-08-29
10,IDR,31.08.2026,360,0.002518,None,Рупія,2026-08-29 11:56:16.108424+00:00,2026-08-29
11,ILS,31.08.2026,376,14.980500,None,Новий ізраїльський шекель,2026-08-29 11:56:16.108434+00:00,2026-08-29
12,JPY,31.08.2026,392,0.279020,None,Єна,2026-08-29 11:56:16.108443+00:00,2026-08-29
13,KZT,31.08.2026,398,0.096048,None,Теньге,2026-08-29 11:56:16.108452+00:00,2026-08-29
14,KRW,31.08.2026,410,0.032410,None,Вона,2026-08-29 11:56:16.108462+00:00,2026-08-29
15,LBP,31.08.2026,422,0.000497,None,Ліванський фунт,2026-08-29 11:56:16.108472+00:00,2026-08-29
16,MYR,31.08.2026,458,11.071600,None,Малайзійський ринггіт,2026-08-29 11:56:16.108481+00:00,2026-08-29
17,MXN,31.08.2026,484,2.627800,None,Мексиканське песо,2026-08-29 11:56:16.108491+00:00,2026-08-29
18,MDL,31.08.2026,498,2.579600,None,Молдовський лей,2026-08-29 11:56:16.108500+00:00,2026-08-29
19,NZD,31.08.2026,554,26.485700,None,Новозеландський долар,2026-08-29 11:56:16.108509+00:00,2026-08-29
20,NOK,31.08.2026,578,4.776700,None,Норвезька крона,2026-08-29 11:56:16.108519+00:00,2026-08-29
21,SAR,31.08.2026,682,11.865700,None,Саудівський ріял,2026-08-29 11:56:16.108528+00:00,2026-08-29
22,SGD,31.08.2026,702,35.041300,None,Сінгапурський долар,2026-08-29 11:56:16.108538+00:00,2026-08-29
23,VND,31.08.2026,704,0.001708,None,Донг,2026-08-29 11:56:16.108563+00:00,2026-08-29
24,ZAR,31.08.2026,710,2.784100,None,Ренд,2026-08-29 11:56:16.108572+00:00,2026-08-29
25,SEK,31.08.2026,752,4.679700,None,Шведська крона,2026-08-29 11:56:16.108582+00:00,2026-08-29
26,CHF,31.08.2026,756,55.420700,None,Швейцарський франк,2026-08-29 11:56:16.108592+00:00,2026-08-29
27,THB,31.08.2026,764,1.351820,None,Бат,2026-08-29 11:56:16.108601+00:00,2026-08-29
28,AED,31.08.2026,784,12.129200,None,Дирхам ОАЕ,2026-08-29 11:56:16.108611+00:00,2026-08-29
29,TND,31.08.2026,788,15.325000,None,Туніський динар,2026-08-29 11:56:16.108620+00:00,2026-08-29
30,EGP,31.08.2026,818,0.886600,None,Єгипетський фунт,2026-08-29 11:56:16.108632+00:00,2026-08-29
31,GBP,31.08.2026,826,60.523200,None,Фунт стерлінгів,2026-08-29 11:56:16.108642+00:00,2026-08-29
32,USD,31.08.2026,840,44.550500,N,Долар США,2026-08-29 11:56:16.108651+00:00,2026-08-29
33,RSD,31.08.2026,941,0.442050,None,Сербський динар,2026-08-29 11:56:16.108660+00:00,2026-08-29
34,AZN,31.08.2026,944,26.206200,None,Азербайджанський манат,2026-08-29 11:56:16.108670+00:00,2026-08-29
35,RON,31.08.2026,946,9.866100,None,Румунський лей,2026-08-29 11:56:16.108679+00:00,2026-08-29
36,TRY,31.08.2026,949,0.923400,None,Турецька ліра,2026-08-29 11:56:16.108693+00:00,2026-08-29
37,XDR,31.08.2026,960,61.082600,None,СПЗ (спеціальні права запозичення),2026-08-29 11:56:16.108703+00:00,2026-08-29
38,EUR,31.08.2026,978,51.880400,None,Євро,2026-08-29 11:56:16.108712+00:00,2026-08-29
39,GEL,31.08.2026,981,17.043400,None,Ларі,2026-08-29 11:56:16.108721+00:00,2026-08-29
40,PLN,31.08.2026,985,11.962500,None,Злотий,2026-08-29 11:56:16.108730+00:00,2026-08-29
41,XAU,31.08.2026,959,204632.030000,None,Золото,2026-08-29 11:56:16.108739+00:00,2026-08-29
42,XAG,31.08.2026,961,3127.580000,None,Срібло,2026-08-29 11:56:16.108748+00:00,2026-08-29
43,XPT,31.08.2026,962,84438.750000,None,Платина,2026-08-29 11:56:16.108757+00:00,2026-08-29
44,XPD,31.08.2026,964,62877.770000,None,Паладій,2026-08-29 11:56:16.108766+00:00,2026-08-29

In [58]:
# Завдання 6.3. Підставте ключі вимірів: date_key — з business_date у форматі YYYYMMDD, currency_key — приєднанням nbu_dwh.dim_currency, з -1 для ненайдених валют.


date_dim_bq = f"""
SELECT *
FROM `{PROJECT_ID}.nbu_dwh.dim_date`
"""

currency_dim_bq = f"""
SELECT *
FROM `{PROJECT_ID}.nbu_dwh.dim_currency`
"""



date_dim = client.query(date_dim_bq).to_dataframe()

payload = payload.merge(
    date_dim[["date_key", "full_date"]],
    left_on="business_date",
    right_on="full_date",
    how="left"
)


currency_dim = client.query(currency_dim_bq).to_dataframe()

payload = payload.merge(
    currency_dim[["currency_key", "currency_code"]],
    left_on="cc",
    right_on="currency_code",
    how="left"
)

payload["dw_load_ts"] = pd.Timestamp.now(tz="UTC")

payload["currency_key"] = payload["currency_key"].fillna(-1).astype("Int64")
        
fact = payload[[
    "date_key", "currency_key", "rate", "business_date", "dw_load_ts"
]]

fact

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,date_key,currency_key,rate,business_date,dw_load_ts
0,20260829,1,0.334950,2026-08-29,2026-08-29 19:04:31.199366+00:00
1,20260829,2,32.049200,2026-08-29,2026-08-29 19:04:31.199366+00:00
2,20260829,3,0.363330,2026-08-29,2026-08-29 19:04:31.199366+00:00
3,20260829,4,32.166200,2026-08-29,2026-08-29 19:04:31.199366+00:00
4,20260829,5,6.628100,2026-08-29,2026-08-29 19:04:31.199366+00:00
5,20260829,6,2.148200,2026-08-29,2026-08-29 19:04:31.199366+00:00
6,20260829,7,6.940800,2026-08-29,2026-08-29 19:04:31.199366+00:00
7,20260829,8,5.682700,2026-08-29,2026-08-29 19:04:31.199366+00:00
8,20260829,9,0.142161,2026-08-29,2026-08-29 19:04:31.199366+00:00
9,20260829,10,0.467030,2026-08-29,2026-08-29 19:04:31.199366+00:00
10,20260829,11,0.002518,2026-08-29,2026-08-29 19:04:31.199366+00:00
11,20260829,12,14.980500,2026-08-29,2026-08-29 19:04:31.199366+00:00
12,20260829,13,0.279020,2026-08-29,2026-08-29 19:04:31.199366+00:00
13,20260829,14,0.096048,2026-08-29,2026-08-29 19:04:31.199366+00:00
14,20260829,15,0.032410,2026-08-29,2026-08-29 19:04:31.199366+00:00
15,20260829,16,0.000497,2026-08-29,2026-08-29 19:04:31.199366+00:00
16,20260829,17,11.071600,2026-08-29,2026-08-29 19:04:31.199366+00:00
17,20260829,18,2.627800,2026-08-29,2026-08-29 19:04:31.199366+00:00
18,20260829,19,2.579600,2026-08-29,2026-08-29 19:04:31.199366+00:00
19,20260829,20,26.485700,2026-08-29,2026-08-29 19:04:31.199366+00:00
20,20260829,21,4.776700,2026-08-29,2026-08-29 19:04:31.199366+00:00
21,20260829,22,11.865700,2026-08-29,2026-08-29 19:04:31.199366+00:00
22,20260829,23,35.041300,2026-08-29,2026-08-29 19:04:31.199366+00:00
23,20260829,24,0.001708,2026-08-29,2026-08-29 19:04:31.199366+00:00
24,20260829,25,2.784100,2026-08-29,2026-08-29 19:04:31.199366+00:00
25,20260829,26,4.679700,2026-08-29,2026-08-29 19:04:31.199366+00:00
26,20260829,27,55.420700,2026-08-29,2026-08-29 19:04:31.199366+00:00
27,20260829,28,1.351820,2026-08-29,2026-08-29 19:04:31.199366+00:00
28,20260829,29,12.129200,2026-08-29,2026-08-29 19:04:31.199366+00:00
29,20260829,30,15.325000,2026-08-29,2026-08-29 19:04:31.199366+00:00
30,20260829,31,0.886600,2026-08-29,2026-08-29 19:04:31.199366+00:00
31,20260829,32,60.523200,2026-08-29,2026-08-29 19:04:31.199366+00:00
32,20260829,33,44.550500,2026-08-29,2026-08-29 19:04:31.199366+00:00
33,20260829,34,0.442050,2026-08-29,2026-08-29 19:04:31.199366+00:00
34,20260829,35,26.206200,2026-08-29,2026-08-29 19:04:31.199366+00:00
35,20260829,36,9.866100,2026-08-29,2026-08-29 19:04:31.199366+00:00
36,20260829,37,0.923400,2026-08-29,2026-08-29 19:04:31.199366+00:00
37,20260829,38,61.082600,2026-08-29,2026-08-29 19:04:31.199366+00:00
38,20260829,39,51.880400,2026-08-29,2026-08-29 19:04:31.199366+00:00
39,20260829,40,17.043400,2026-08-29,2026-08-29 19:04:31.199366+00:00
40,20260829,41,11.962500,2026-08-29,2026-08-29 19:04:31.199366+00:00
41,20260829,42,204632.030000,2026-08-29,2026-08-29 19:04:31.199366+00:00
42,20260829,43,3127.580000,2026-08-29,2026-08-29 19:04:31.199366+00:00
43,20260829,44,84438.750000,2026-08-29,2026-08-29 19:04:31.199366+00:00
44,20260829,45,62877.770000,2026-08-29,2026-08-29 19:04:31.199366+00:00

In [59]:
# Завдання 6.4. Створіть таблицю nbu_dwh.fact_exchange_rate, якщо її ще немає: схема з пункту 6.3, партиціювання за business_date, кластеризація за currency_key.

fact_id = f"{PROJECT_ID}.nbu_dwh.fact_exchange_rate"

schema = [
    bigquery.SchemaField("date_key", "INT64"),
    bigquery.SchemaField("currency_key", "INT64"),
    bigquery.SchemaField("rate", "FLOAT64"),
    bigquery.SchemaField("business_date", "DATE"),
    bigquery.SchemaField("dw_load_ts", "TIMESTAMP")
]

table = bigquery.Table(fact_id, schema=schema)
table.time_partitioning = bigquery.TimePartitioning(field="business_date")
table.clustering_fields = ["currency_key"]
client.create_table(table, exists_ok=True)

print("Table fact_exchange_rate created!")

Table fact_exchange_rate created!

In [60]:
# Завдання 6.5. Реалізуйте злиття: рядки за сьогодні мають бути оновлені або додані, рядки за попередні дні — залишитися недоторканими.


# 1) уся історія, КРІМ сьогодні
old = client.query(f"""
    SELECT date_key, currency_key, rate, business_date, dw_load_ts
    FROM `{fact_id}`
    WHERE business_date <> CURRENT_DATE()
""").to_dataframe()

# 2) склеюємо з новою порцією
merged = pd.concat([old, fact], ignore_index=True)

# 3) перезаписуємо таблицю цілком
cfg = bigquery.LoadJobConfig(schema=schema, write_disposition="WRITE_TRUNCATE")
client.load_table_from_dataframe(merged, fact_id, job_config=cfg).result()

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=datalab-504011, location=EU, id=32b08205-209f-44f3-8c23-97c5a6a0edce>

In [61]:
# Завдання 6.6. Перевірте й виведіть результат трьома запитами:

# Checking for duplicates

query = f"""
SELECT date_key, currency_key, COUNT(*) AS cnt
FROM `{fact_id}`
GROUP BY date_key, currency_key
HAVING COUNT(*) > 1
"""

duplicates = client.query(query).to_dataframe()

print("Grain is unique:", len(duplicates) == 0)


# кількість різних business_date у таблиці;
query_business_day_duplicates = f"""
SELECT COUNT(DISTINCT business_date) AS date_count
FROM `{fact_id}`                 
"""

result_days = client.query(query_business_day_duplicates).to_dataframe()

print("Different business dates:", result_days["date_count"].iloc[0])


# загальна кількість рядків.

number_of_rows = f"""
SELECT COUNT(*) cnt
FROM `{fact_id}`
"""

num_rows = client.query(number_of_rows).to_dataframe()
print("Total rows:", num_rows["cnt"].iloc[0])

Grain is unique: True
Different business dates: 1
Total rows: 45

/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/opt/python/envs/default_3_11/lib/python3.11/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(